# Generated by Django 5.1.2 on 2025-03-04 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv1', '0002_alter_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
